// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hzonuhhsvqpeinrdguty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6b251aGhzdnFwZWlucmRndXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDU5NDQsImV4cCI6MjA2NzA4MTk0NH0.718dRysKEIhbrdSrsGXI0gvKrAfrhzueRqiQCK71jKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);